### ISSUE TITLE
Ubuntu mirror host `mirrors.byrio.org` is outdated.

### ISSUE THREAD

**Issue by siteshen** [BYRIO/BYRIO-mirrors#11]
```
ping: cannot resolve mirrors.byrio.org: Unknown host
```
Hostname from webpage: https://mirrors.bupt.edu.cn/help/ubuntu/

**Comment by FredericDT** [comment]
Please consider mirrors.bupt.edu.cn when you only have IPv4 access.

**Comment by siteshen** [comment]
> Please consider mirrors.bupt.edu.cn when you only have IPv4 access.

OK, thanks.
