### ISSUE TITLE
请求开放同步状态数据的跨域访问

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [BYRIO/BYRIO-mirrors#7]
同步状态数据的 url 是 https://mirrors.byrio.org/static/tunasync.json ，该数据也可用于其他项目（例如 [mirrorz](https://mirrorz.org)），故请求开放其跨域访问，或者几个特定站的跨域访问。

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

参考 https://github.com/PKUOSC/issues/issues/2

**Comment by FredericDT** [comment]
已按请求授权 https://mirrorz.org 跨域访问本站 /static/tunasync.json
